version: '3.8'
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672" # painel admin

  translation-api:
    build: ./translation-api
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - rabbitmq

  translation-worker:
    build: ./translation-worker
    depends_on:
      - mongo
      - rabbitmq
